[paths]
build-dir = "../../../botw-decomp/build"
elf = "../../../botw-decomp/build/uking"
compdb = "../../../botw-decomp/build/compile_commands.json"
system-header-paths = [
    "../../../botw-decomp/toolchain/clang-4.0.1/include/c++/v1"
]
extract-output = "dejj"

[paths.functions-csv]
path = "../../../botw-decomp/data/uking_functions.csv"
base-address = 0x7100000000
address-column = 0
symbol-column = 3
skip-rows = 1

[paths.data-csv]
path = "../../../botw-decomp/data/data_symbols.csv"
base-address = 0x7100000000
address-column = 0 
symbol-column = 1

[extract]
build-command = ["ninja"]
build-command-inherit-io = false
pointer-width = 64
ptmd-repr = ["u64", 1]
ptmf-repr = ["u64", 2]
char-repr = "u8"
wchar-repr = "u32"
vfptr-field-regex = "^_vptr\\$"
debug.l2mcache = false
debug.lstage = false
debug.mstage = true
debug.hstage = true

[extract.type-parser]
abandon-typedefs = [
    # these may have unparsable consteval expressions in the templates
    "^std::__1::aligned_storage_t",
    "^std::__1::conditional_t",
    "^std::__1::add_pointer_t",
    "^std::__1::remove_reference_t",
    "^std::__1::__optional_sfinae_assign_base_t",
    "^std::__1::__optional_sfinae_ctor_base_t",

    # nn::gfx::InfoType typedefs
    "^InfoType$",

    # uking::Factory conflicts for both Ai factory and Action factory
    "^uking::Factory$",
]

[extract.type-optimizer]
only-keep-referenced-from-symbols = false
pick-union-member = [
    { regex = "^std::__1::string$", members = ["__l", "__s", "__r"], pick = 0 },
    { regex = "^fpos_t$", members = ["__opaque", "__lldata", "__align"], pick = 0 },

    # below may not be technically accurate, but simplifies the layout so the output
    # is nicer in most cases in the decompiler
    { regex = "^nn::util::BinTPtr<", members = ["_offset", "_ptr"], pick = 1 },
    { regex = "^nn::util::Bin.+Signature$", members = ["_str", "_packed"], pick = 0 },
    { regex = "^uking::ui::PouchItem::Data$", members = ["cook", "weapon"], pick = 0 },
]
enumeratorize = [
    # file: src/Game/DLC/aocHardModeManager.h
    ["^uking::aoc::HardModeManager::HardModeChange$", "^uking::aoc::HardModeManager::HardModeChange::ValueType$"],
    ["^uking::aoc::HardModeManager::Flag$", "^uking::aoc::HardModeManager::Flag::ValueType$"],
    ["^uking::aoc::HardModeManager::MultiplierType$", "^uking::aoc::HardModeManager::MultiplierType::ValueType$"],
    # file: src/Game/DLC/aocManager.h
    ["^uking::aoc::Manager::GameDataFlag$", "^uking::aoc::Manager::GameDataFlag::ValueType$"],
    ["^uking::aoc::Manager::VersionError$", "^uking::aoc::Manager::VersionError::ValueType$"],

    # file: src/KingSystem/ActorSystem/Attention/actAttention.h
    ["^ksys::act::AttActionType$", "^ksys::act::AttActionType::ValueType$"],
    ["^ksys::act::AttPriorityType$", "^ksys::act::AttPriorityType::ValueType$"],
    # file: src/KingSystem/ActorSystem/Awareness/actAwareness.h
    ["^ksys::act::Awareness::Flag$", "^ksys::act::Awareness::Flag::ValueType$"],
    # file: src/KingSystem/Event/evtActorBinding.h
    ["^ksys::evt::ActorBinding::ActorCreateMode$", "^ksys::evt::ActorBinding::ActorCreateMode::ValueType$"],
    # file: src/KingSystem/GameData/gdtFlag.h
    ["^ksys::gdt::FlagType$", "^ksys::gdt::FlagType::ValueType$"],
    # file: src/KingSystem/Physics/physDefines.h
    ["^ksys::phys::ContactLayer$", "^ksys::phys::ContactLayer::ValueType$"],
    ["^ksys::phys::Material$", "^ksys::phys::Material::ValueType$"],
    ["^ksys::phys::GroundHit$", "^ksys::phys::GroundHit::ValueType$"],
    ["^ksys::phys::FloorCode$", "^ksys::phys::FloorCode::ValueType$"],
    ["^ksys::phys::WallCode$", "^ksys::phys::WallCode::ValueType$"],
    # file: src/KingSystem/Physics/physMaterialMask.h
    ["^ksys::phys::MaterialMaskData::CustomFlag$", "^ksys::phys::MaterialMaskData::CustomFlag::ValueType$"],
    # file: src/KingSystem/Physics/System/physCharacterControllerParam.h
    ["^ksys::phys::NavMeshCharacterType$", "^ksys::phys::NavMeshCharacterType::ValueType$"],
    # file: src/KingSystem/Physics/System/physSystemData.h
    ["^ksys::phys::CharacterControllerTable::Type$", "^ksys::phys::CharacterControllerTable::Type::ValueType$"],
    # file: src/KingSystem/Resource/resUnit.h
    ["^ksys::res::ResourceUnit::Status$", "^ksys::res::ResourceUnit::Status::ValueType$"],
    # file: src/KingSystem/Resource/Actor/resResourceDamageParam.h
    ["^ksys::res::DamageParam::DamageSize$", "^ksys::res::DamageParam::DamageSize::ValueType$"],
    ["^ksys::res::DamageParam::DamageSource$", "^ksys::res::DamageParam::DamageSource::ValueType$"],

    # file: src/KingSystem/Sound/sndMusicInfo.h
    ["^ksys::snd::EnvBgmInfo::EnvTimeEnum$", "^ksys::snd::EnvBgmInfo::EnvTimeEnum::ValueType$"],
    ["^ksys::snd::TemperatureBgmInfo::TemperatureEnum$", "^ksys::snd::TemperatureBgmInfo::TemperatureEnum::ValueType$"],
    ["^ksys::snd::DragonBgmInfo::DragonEnum$", "^ksys::snd::DragonBgmInfo::DragonEnum::ValueType$"],
    ["^ksys::snd::EnvPaletteReactiveBgmInfo::EnvPaletteReactiveBgmEnum$", "^ksys::snd::EnvPaletteReactiveBgmInfo::EnvPaletteReactiveBgmEnum::ValueType$"],
    # file: src/KingSystem/System/ProductReporter.h
    ["^ksys::PlayReportKey$", "^ksys::PlayReportKey::ValueType$"],
    # file: src/KingSystem/World/worldDefines.h
    ["^ksys::world::DungeonSize$", "^ksys::world::DungeonSize::ValueType$"],
    ["^ksys::world::DungeonType$", "^ksys::world::DungeonType::ValueType$"],
    # file: src/KingSystem/World/worldTimeMgr.h
    ["^ksys::world::TimeType$", "^ksys::world::TimeType::ValueType$"],
    ["^ksys::world::TimeDivision$", "^ksys::world::TimeDivision::ValueType$"],

    # file: lib/EventFlow/include/evfl/Action.h
    ["^evfl::TriggerType$", "^evfl::TriggerType::Type$"],
    # file: lib/EventFlow/include/evfl/Flowchart.h
    ["^evfl::SubFlowCallbackType$", "^evfl::SubFlowCallbackType::Type$"],
    ["^evfl::FlowchartContextMode::State$", "^evfl::FlowchartContextMode::State::Type$"],
    ["^evfl::FlowchartContext::Builder::BuildResultType$", "^evfl::FlowchartContext::Builder::BuildResultType::Type$"],
    # file: lib/EventFlow/include/evfl/Param.h
    ["^evfl::MetaDataPack::DataType$", "^evfl::MetaDataPack::DataType::Type$"],
    # file: lib/EventFlow/include/evfl/Query.h
    ["^evfl::QueryValueType$", "^evfl::QueryValueType::Type$"],
    # file: lib/EventFlow/include/evfl/ResFlowchart.h
    ["^evfl::ResEvent::EventType$", "^evfl::ResEvent::EventType::Type$"],
    # file: lib/EventFlow/include/evfl/TimelineObj.h
    ["^evfl::TimelineState$", "^evfl::TimelineState::Type$"],
    # file: lib/EventFlow/include/ore/ResMetaData.h
    ["^ore::ResMetaData::DataType$", "^ore::ResMetadata::DataType::Type$"],
    ["^ore::ResUserData::DataType$", "^ore::ResUserData::DataType::Type$"],

    # file: lib/gsys/src/gsys/gsysModelSceneConfig.cpp
    ["^gsys::DepthFormat$", "^gsys::DepthFormat::ValueType$"],
    ["^gsys::DepthShadowMapFormat$", "^gsys::DepthShadowMapFormat::ValueType$"],

    # file: lib/sead/include/devenv/seadEnvUtil.h
    ["^sead::RegionID$", "^sead::RegionID::ValueType$"],
    ["^sead::RegionLanguageID$", "^sead::RegionLanguageID::ValueType$"],
    # file: lib/sead/include/heap/seadHeap.h
    ["^sead::Heap::Flag$", "^sead::Heap::Flag::ValueType$"],
    # file: lib/sead/include/mc/seadCoreInfo.h
    ["^sead::CoreId$", "^sead::CoreId::ValueType$"],
    # file: lib/sead/include/mc/seadJobQueue.h
    ["^sead::SyncType$", "^sead::SyncType::ValueType$"],
    # file: lib/sead/include/mc/seadWorker.h
    ["^sead::JobQueuePushType$", "^sead::JobQueuePushType::ValueType$"],
    ["^sead::Worker::State$", "^sead::Worker::State::ValueType$"],
    # file: lib/sead/include/thread/seadThread.h
    ["^sead::Thread::State$", "^sead::Thread::State::ValueType$"],

]
#
#
# [extract.name-resolution.override]
# # de-templatize
# "^sead::OffsetList<.*>$" = "sead::OffsetList"
# "^sead::DelegateEvent<.*>$" = "sead::DelegateEvent"

# [extract.type-optimizer.opaque-if]
# name-matches = [
#     "^std::__va_list$", 
# ]
# struct-member-name-contains = [
#     "__clang"
# ]

[extract.name-resolution]
rules = []
test = []
